language: objective-c
before_install:
- gem install cocoapods
before_script:
- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/profile/JanuaryAdHoc.mobileprovision.enc
  -d -a -out scripts/profile/JanuaryAdHoc.mobileprovision
- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/certs/dist.p12.enc -d -a
  -out scripts/certs/dist.p12
- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/certs/dist.cer.enc -d -a
  -out scripts/certs/dist.cer
- ./scripts/add-key.sh
- ./scripts/update-bundle.sh
script:
- xctool -workspace January.xcworkspace -scheme January -sdk iphoneos -configuration
  Release OBJROOT=$PWD/build SYMROOT=$PWD/build ONLY_ACTIVE_ARCH=NO
after_success:
- ./scripts/sign-and-upload.sh
after_script:
- ./scripts/remove-key.sh
env:
  global:
  - APP_NAME="January"
  - 'DEVELOPER_NAME="iPhone Distribution: Vitaliy Berg (5G5YZAQBSX)"'
  - PROFILE_NAME="JanuaryAdHoc"
  - INFO_PLIST="January/January-Info.plist"
  - secure: T1IyOu5s1VONaifTHmGDvKcCxmPg3ITk0NmUXUALpKVKgYZSmdwkGxX/W/wsepLUyz+MbyuPUbQJXNQEPUfsx6CYP4yfl37/upMT878dYxYPTFwprTelf9a9DSvNdT85Oj8efOkAU8Mwd2mo0vGUgv3EhBLztN/IJKbSMpBFxSU=
  - secure: uN1Cena9CLlGDP3s9NqqYGx5MH3+YfsK1LimhleQHDnitBXI+QgE3kTEYc1Cyq+WtYiDuiUgS19w5apM5oL75VjZunADRhfBpho8RevLRtiT/oh689YNemdLih5sk50NO0lAq+NUHwrsPwwRVTlkQgOaE9pONxfWRqpvwkL9HLc=
  - secure: AzqFRHK3V25aA6rgoXGHwRFylHb+JWP3t3285qJbnz1Gy0O9J+X/ho4hOtnPuesTQRrn+NRapdv8002PiNdaDzxyB69zY9WGaDsiGJNfGQeehs0zuCZV7gC26QW5lEWtTSrKdBMPMZJzNSPgsNUccS82oUZrxUPSET6MKCSNGcM=
  - secure: kh2rSIFqAH0H6ziyGkQRyETuJht2YUWYTzhXltzTQU6H8jFpVdz/XYtr81soaXah+vNfmG8P2WrWCHHHebAyU0VtXwnWMnsCYd2f1zbC9c7bwbNNYJTexe6Iw0wnpVQh2e1zPhslKgy+ZjVqHKJGmiMV9MuUwcaTKs0GiyJ6AOM=
